team_mapping = {
    "LA": {"nome": "Los Angeles Rams", "cor": "#003594"},
    "BUF": {"nome": "Buffalo Bills", "cor": "#00338D"},
    "ATL": {"nome": "Atlanta Falcons", "cor": "#A71930"},
    "NO": {"nome": "New Orleans Saints", "cor": "#D3BC8D"},
    "CAR": {"nome": "Carolina Panthers", "cor": "#0085CA"},
    "CLE": {"nome": "Cleveland Browns", "cor": "#311D00"},
    "CHI": {"nome": "Chicago Bears", "cor": "#0B162A"},
    "SF": {"nome": "San Francisco 49ers", "cor": "#AA0000"},
    "CIN": {"nome": "Cincinnati Bengals", "cor": "#FB4F14"},
    "PIT": {"nome": "Pittsburgh Steelers", "cor": "#FFB612"},
    "DET": {"nome": "Detroit Lions", "cor": "#0076B6"},
    "PHI": {"nome": "Philadelphia Eagles", "cor": "#004C54"},
    "HOU": {"nome": "Houston Texans", "cor": "#03202F"},
    "IND": {"nome": "Indianapolis Colts", "cor": "#002C5F"},
    "MIA": {"nome": "Miami Dolphins", "cor": "#008E97"},
    "NE": {"nome": "New England Patriots", "cor": "#002244"},
    "NYJ": {"nome": "New York Jets", "cor": "#125740"},
    "BAL": {"nome": "Baltimore Ravens", "cor": "#241773"},
    "WAS": {"nome": "Washington Commanders", "cor": "#5A1414"},
    "JAX": {"nome": "Jacksonville Jaguars", "cor": "#006778"},
    "ARI": {"nome": "Arizona Cardinals", "cor": "#97233F"},
    "KC": {"nome": "Kansas City Chiefs", "cor": "#E31837"},
    "LAC": {"nome": "Los Angeles Chargers", "cor": "#0080C6"},
    "LV": {"nome": "Las Vegas Raiders", "cor": "#000000"},
    "MIN": {"nome": "Minnesota Vikings", "cor": "#4F2683"},
    "GB": {"nome": "Green Bay Packers", "cor": "#203731"},
    "TEN": {"nome": "Tennessee Titans", "cor": "#4B92DB"},
    "NYG": {"nome": "New York Giants", "cor": "#0B2265"},
    "DAL": {"nome": "Dallas Cowboys", "cor": "#041E42"},
    "TB": {"nome": "Tampa Bay Buccaneers", "cor": "#D50A0A"},
    "SEA": {"nome": "Seattle Seahawks", "cor": "#002244"},
    "DEN": {"nome": "Denver Broncos", "cor": "#FB4F14"},
}
